# Generated by Django 5.1.6 on 2025-04-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('book', 'Book'), ('magazine', 'Magazine'), ('digital', 'Digital Media')], max_length=20)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('issue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('item_format', models.CharField(blank=True, max_length=50, null=True)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='DigitalMedia',
        ),
        migrations.DeleteModel(
            name='Magazine',
        ),
    ]
