-- sql/04_print_contents.sql
SELECT * FROM django_content_type;
SELECT * FROM auth_user;
SELECT * FROM accounts_user;
SELECT * FROM auth_group;
SELECT * FROM auth_permission;
SELECT * FROM auth_group_permissions;
SELECT * FROM auth_user_groups;
SELECT * FROM auth_user_user_permissions;
SELECT * FROM accounts_user_user_permissions;
SELECT * FROM accounts_user_groups;
SELECT * FROM catalog_item;
SELECT * FROM reservations_reservation;
SELECT * FROM loans_reservation;
SELECT * FROM loans_borrowingtransaction;
SELECT * FROM reports_report;
SELECT * FROM notifications_notification;
SELECT * FROM core_auditing;
SELECT * FROM core_systemconfig;
