# Generated by Django 5.1.6 on 2025-04-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('premium', 'Premium'), ('none', 'None')], max_length=20, null=True),
        ),
    ]
